'use strict';
//####### 7 questions about me  ###########

let correctQuest = 0;
let randomNumber = Math.floor(Math.random() * 11);
let q6GuessLeft = 4;
let q7GuessLeft = 6;
let correctGuess = false;
let arrayOfAnswers = [
  ['yes', 'y'],
  ['no', 'n'],
  [randomNumber],
  ['teriyaki', 'pho', 'thai', 'steak']
];
console.log(`Cheating message! Random Number is: ${arrayOfAnswers[2][0]}`); // Prints out number generated by randomNumber

// First Question
let firstQ = function () {
  let catLower = prompt('Do you think I like Cats? Please enter Yes or No').toLowerCase();
  // Checking to see if user answer comes out as 'yes' or 'y'
  if (catLower === arrayOfAnswers[0][0] || catLower === arrayOfAnswers[0][1]) {
    correctQuest++; //Adds a point when answered correctly
    return alert('That\'s amazing! You are spot on!');
  } else {
    return alert('I\'m so sorry you got this wrong... You must be a dog person huh...');
  }
};

// Second Question
let bake = prompt('Do you think I like to Bake? Please enter Yes or No').toLowerCase();
// Checking to see if user answer comes out as 'yes' or 'y'
if (bake === arrayOfAnswers[0][0] || bake === arrayOfAnswers[0][1]) {
  correctQuest++; //Adds a point when answered correctly
  alert('That\'s amazing! I love Pastries');
} else {
  alert('You sir, need some sugar in your life! But, if you can not, I will still be friends with you.');
}

//Third Question
let live = prompt('Do I live in Bothell, WA? Please enter Yes or No').toLowerCase();
// Checking to see if user answer comes out as 'yes' or 'y'
if (live === arrayOfAnswers[1][0] || live === arrayOfAnswers[1][1]) {
  correctQuest++; //Adds a point when answered correctly
  alert('You... You didn\'t read... my... about me... Seriously?');
} else {
  alert('Your correct! I actually live in Renton!');
}

//Fourth Question
let outDoor = prompt('Do you think I like the outdoors? Please enter Yes or No').toLowerCase();
// Checking to see if user answer comes out as 'yes' or 'y'
if (outDoor === arrayOfAnswers[0][0] || outDoor === arrayOfAnswers[0][1]) {
  correctQuest++; //Adds a point when answered correctly
  alert('Your correct! I actually like the outdoors!');
} else {
  alert('Looks like you need to go outdoors more then me... I like going outdoors..?');
}

//Fifth Question
let catMany = prompt('Do you think I have over 10 cats? Please enter Yes or No').toLowerCase();
// Checking to see if user answer comes out as 'yes' or 'y'
if (catMany === arrayOfAnswers[1][0] || catMany === arrayOfAnswers[1][1]) {
  correctQuest++; //Adds a point when answered correctly
  alert('Your correct! I do not have 10! I just have 2!');
} else {
  alert('Although it would be great to have 10, I do not have 10!');
}

//Sixth Question
// Four Attempts
let i; // Line 91 will not run if calling in for loop
for (i = 0; i < 4; i++) {
  let guessing = parseInt(prompt('Pick a Number Between 1 and 10')); // returns an interger
  q6GuessLeft--;
  // Checking if user guess is the same as random number stored in array
  if (guessing === arrayOfAnswers[2][0]) {
    correctQuest++; //Adds a point when answered correctly
    alert(`Your correct! ${guessing} is correct!`);
    break;
  }
  else if (guessing <= arrayOfAnswers[2][0]) {
    alert(`Your guess of ${guessing} was too low!! You have ${q6GuessLeft} guesses left`);
  }
  else if (guessing >= arrayOfAnswers[2][0]) {
    alert(`Your guess of ${guessing} was too high!! You have ${q6GuessLeft} guesses left`);
  }
  else { // In case the user does not insert a number
    alert(`Please enter a number between 1 and 10 You have ${q6GuessLeft} guesses left`);
  }
}
alert(`The correct answer was ${arrayOfAnswers[2][0]}!`); // returns the answer of random number
alert(`You guessed a total of ${i + 1} times!`); // returns amount of guesses user did

// 7th Question
// Six attempts
for (let o = 1; o <= 6; o++) { // Running 6 times for 6 total guesses
  q7GuessLeft--;
  // If user answers correctly, will flip and run if statement, breaking out of outer four loop
  if (correctGuess) {
    break;
  }
  let guessing = prompt('What do you think might be one of my favorite foods?').toLowerCase();
  for (let f = 0; f < arrayOfAnswers[3].length; f++) { // Loops through the array to compare answers with array
    // Checks to see if answer is inside the array
    if (guessing === arrayOfAnswers[3][f]) {
      correctQuest++; //Adds a point when answered correctly
      correctGuess = true; // Once answers correctly, flips the first if statement, breaking out of first four loop
      alert(`Your guess of ${guessing} is correct! Nicely done!`);
      break; // Saves 0.000000001 seconds
    }
  }
  //If question is false, if will run, once correct, will not run
  if (!correctGuess){
    alert(`Your answer ${guessing} is wrong, please pick again! You have ${q7GuessLeft} guesses left`);
  }
}
alert(`The correct answers are: ${arrayOfAnswers[3]}`); // Displays correct answers
alert(`The amount of questions answered correctly was ${correctQuest}`);

// test
