'use strict';
//####### 7 questions about me  ###########
let correctQuest = 0;
let randomNumber = Math.floor(Math.random() * 11);
let q6GuessLeft = 4;
let q7GuessLeft = 6;
let correctGuess = false;
let arrayOfAnswers = [
  ['yes', 'y'],
  ['no', 'n'],
  [randomNumber],
  ['teriyaki', 'pho', 'thai', 'steak']
];
let arrayOfQuestions = [
  ['Do you think I like Cats? Please enter Yes or No','Do you think I like to Bake? Please enter Yes or No', 'Do I live in Bothell, WA? Please enter Yes or No','Do you think I like the outdoors? Please enter Yes or No', 'Do you think I have over 10 cats? Please enter Yes or No','Pick a Number Between 1 and 10', 'What do you think might be one of my favorite foods?']
];
let arrayOfReturns = [
  ['That\'s amazing! You are spot on!','I\'m so sorry you got this wrong... You must be a dog person huh...'],
  ['That\'s amazing! I love Pastries','You sir, need some sugar in your life! But, if you can not, I will still be friends with you.'],
  ['You... You didn\'t read... my... about me... Seriously?','Your correct! I don\'t live in Bothell, I actually live in Renton!'],
  ['Your correct! I actually like the outdoors!', 'Looks like you need to go outdoors more then me... I like going outdoors..?'],
  ['Your correct! I do not have 10! I just have 2!','Although it would be great to have 10, I do not have 10!'],
  ['Your guess of ',' is correct! Nicely done!', 'Your answer ',' is wrong, please pick again! You have ',' guesses left']
];
console.log(`Cheating message! Random Number is: ${arrayOfAnswers[2][0]}`); // Prints out number generated by randomNumber

// First Question
function q1() {
  let catLower = prompt(arrayOfQuestions[0][0]).toLowerCase();
  console.log('catLower');
  // Checking to see if user answer comes out as 'yes' or 'y'
  if (catLower === arrayOfAnswers[0][0] || catLower === arrayOfAnswers[0][1]) {
    correctQuest++; //Adds a point when answered correctly
    return alert(arrayOfReturns[0][0]);
  } else {
    return alert(arrayOfReturns[0][1]);
  }
}
q1();
// Second Question
function q2() {
  let bake = prompt(arrayOfQuestions[0][1]).toLowerCase();
  console.log('bake');
  // Checking to see if user answer comes out as 'yes' or 'y'
  if (bake === arrayOfAnswers[0][0] || bake === arrayOfAnswers[0][1]) {
    correctQuest++; //Adds a point when answered correctly
    alert(arrayOfReturns[1][0]);
  }  else {
    alert(arrayOfReturns[1][1]);
  }
}
q2();
//Third Question
function q3() {
  let live = prompt(arrayOfQuestions[0][2]).toLowerCase();
  console.log('live');
  // Checking to see if user answer comes out as 'yes' or 'y'
  if (live === arrayOfAnswers[1][0] || live === arrayOfAnswers[1][1]) {
    correctQuest++; //Adds a point when answered correctly
    alert(arrayOfReturns[2][0]);
  } else {
    alert(arrayOfReturns[2][1]);
  }
}
q3();
//Fourth Question
function q4() {
  let outDoor = prompt(arrayOfQuestions[0][3]).toLowerCase();
  console.log('outDoor');
  // Checking to see if user answer comes out as 'yes' or 'y'
  if (outDoor === arrayOfAnswers[0][0] || outDoor === arrayOfAnswers[0][1]) {
    correctQuest++; //Adds a point when answered correctly
    alert(arrayOfReturns[3][0]);
  } else {
    alert(arrayOfReturns[3][1]);
  }
}
q4();
//Fifth Question
function q5() {
  let catMany = prompt(arrayOfQuestions[0][4]).toLowerCase();
  console.log('catMany');
  // Checking to see if user answer comes out as 'yes' or 'y'
  if (catMany === arrayOfAnswers[1][0] || catMany === arrayOfAnswers[1][1]) {
    correctQuest++; //Adds a point when answered correctly
    alert(arrayOfReturns[4][0]);
  } else {
    alert(arrayOfReturns[4][1]);
  }
}
q5();
//Sixth Question
// Four Attempts
let i; // Line 91 will not run if calling in for loop
function q6() {
  for (i = 0; i < 4; i++) {
    let guessing = parseInt(prompt(arrayOfQuestions[0][5])); // returns an interger
    console.log('guessing');
    q6GuessLeft--;
    // Checking if user guess is the same as random number stored in array
    if (guessing === arrayOfAnswers[2][0]) {
      correctQuest++; //Adds a point when answered correctly
      alert(`Your correct! ${guessing} is correct!`);
      break;
    }
    else if (guessing <= arrayOfAnswers[2][0]) {
      alert(`Your guess of ${guessing} was too low!! You have ${q6GuessLeft} guesses left`);
    }
    else if (guessing >= arrayOfAnswers[2][0]) {
      alert(`Your guess of ${guessing} was too high!! You have ${q6GuessLeft} guesses left`);
    }
    else { // In case the user does not insert a number
      alert(`Please enter a number between 1 and 10 You have ${q6GuessLeft} guesses left`);
    }
  }
  alert(`The correct answer was ${arrayOfAnswers[2][0]}!`); // returns the answer of random number
  alert(`You guessed a total of ${i + 1} times!`); // returns amount of guesses user did
}
q6();
// 7th Question
// function quickMessage(guess) {
//   let message =
// }

// Six attempts
function q7() {
  for (let o = 1; o <= 6; o++) { // Running 6 times for 6 total guesses
    console.log('correctGuess');
    q7GuessLeft--;
    // If user answers correctly, will flip and run if statement, breaking out of outer four loop
    if (correctGuess) {
      break;
    }
    let guessing = prompt(arrayOfQuestions[0][6]).toLowerCase();
    for (let f = 0; f < arrayOfAnswers[3].length; f++) { // Loops through the array to compare answers with array
      // Checks to see if answer is inside the array
      if (guessing === arrayOfAnswers[3][f]) {
        correctQuest++; //Adds a point when answered correctly
        correctGuess = true; // Once answers correctly, flips the first if statement, breaking out of first four loop
        alert(arrayOfReturns[5][0] + guessing + arrayOfReturns[5][1]);
        break; // Saves 0.000000001 seconds
      }
    }
    //If question is false, if will run, once correct, will not run
    if (!correctGuess){
      alert(arrayOfReturns[5][2] + guessing + arrayOfReturns[5][3] + q7GuessLeft + arrayOfReturns[5][4]);
    }
  }
  alert(`The correct answers are: ${arrayOfAnswers[3]}`); // Displays correct answers
  alert(`The amount of questions answered correctly was ${correctQuest}`);
}
q7();
// test
